gh-actions: update 'artifact' actions
It was failing with:

Error: This request has been automatically failed because it uses a
deprecated version of `actions/upload-artifact: v2`. Learn more:
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Upgrading directly to 'v4' isn't straightforward, given it includes
breaking changes[1]. Instead of uploading the whole folder, files are
uploaded individually and then downloaded together.

[1]: https://github.com/actions/upload-artifact/issues/478